version: 1
jobs:
  hello:
    steps:
    - cd photo-store-app
    - npm install
    - npm run build
    - cd ..
    - node ./scripts/filesHelper.js -c ./server/ ./build/server/
    - node ./scripts/filesHelper.js -c ./photo-store-app/build/ ./build/photo-store-app/

    artifacts:
        upload:
            - type: file
              name: appsail.zip
              file: /build/**
              location: stratus://<< Test >>/

  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
variables:
  var_test: Run