version: 1
jobs:
  install:
    steps:
    - cd photo-store-app
    - npm install

  compile:
    steps:
        - npm run build
  copy-files:
    steps:
        - cd ..
        - node ./scripts/filesHelper.js -c ./server/ ./build/server/
        - node ./scripts/filesHelper.js -c ./photo-store-app/build/ ./build/photo-store-app/

  deploy:
    steps:
        - npm install -g zcatalyst-cli@beta
        - catalyst deploy
stages:
  - name: build
    jobs:
        - install
        - compile
        - copy-files
        - deploy
variables:
  var_test: Run